#include "userheader.h"
#ifndef functions
#define functions
    void bool_test();
    void bit_sizes();
    void string_test();
    void const_test();
    void typeof_test();
    void type_cast_test();
    void bitwise_unary_logical();
    void division_multiplication();
    void shifting();
    void ifThenElse();
    void roullete();
    void passed_grade();
    void random_number();    
    void arrays();
    void multi_dimensional_arrays();
    void arrays_test();
    void StyleCString();
    void person_struct_test();
    void union_test();
    void enum_test();
    void pointer2ptr();
    void pointer_arrays();
    void delete_pointer_array();
    void multi_dimensioned_array_pointer();
    void pointer_to_cstyle_strings();
    void struct_pointer_linked();
    void auto_pointer();
    void const_pointer_rules();
    void casting_pointers();
    void command_lines();
#endif